In [1]:
import cv2
import numpy as np
import rosbag
from cv_bridge import CvBridge

from sensor_msgs.msg import Image

In [14]:
bag = rosbag.Bag('test_2020-06-15-19-36-39.bag')
bridge = CvBridge()

msgFlow = []
optFlow = []

for topic, msg, t in bag.read_messages(topics=['/flow']):
    msgFlow.append(bridge.imgmsg_to_cv2(msg, 'bgr16'))
    optFlow.append(np.flip(msgFlow[-1][...,1:3], axis=-1).astype(np.float32))
    optFlow[-1] = (optFlow[-1] - 32768.) / (64.)

sample = 60
print("msg")
print(msgFlow[sample][...,1])
print(msgFlow[sample][...,2])

print("flow")
print(optFlow[sample][...,0])
print(optFlow[sample][...,1])

print(np.amax(optFlow[sample][...,0]))
print(np.amax(optFlow[sample][...,1]))

msg
[[32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 ...
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]]
[[32758 32762 32766 ... 32770 32770 32770]
 [32758 32762 32765 ... 32773 32773 32773]
 [32759 32761 32763 ... 32776 32776 32776]
 ...
 [32762 32762 32761 ... 32820 32820 32820]
 [32762 32762 32761 ... 32820 32820 32820]
 [32762 32762 32761 ... 32820 32820 32820]]
flow
[[-0.15625  -0.09375  -0.03125  ...  0.03125   0.03125   0.03125 ]
 [-0.15625  -0.09375  -0.046875 ...  0.078125  0.078125  0.078125]
 [-0.140625 -0.109375 -0.078125 ...  0.125     0.125     0.125   ]
 ...
 [-0.09375  -0.09375  -0.109375 ...  0.8125    0.8125    0.8125  ]
 [-0.09375  -0.09375  -0.109375 ...  0.8125    0.8125    0.8125  ]
 [-0.09375  -0.09375  -0.109375 ...  0.8125    0.8125    0.8125  ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 

In [22]:
cvImage = cv2.imread('000000_10_pr.png', -1)
print(cvImage[...,1])
print(cvImage[...,2])

test1 = np.flip(cvImage[...,1:3], axis=-1).astype(np.float32)
test1 = (test1 - 32768.) / (64.)

print(test1[...,0])
print(test1[...,1])
print(np.amax(test1[...,0]))
print(np.amax(test1[...,1]))
print(np.amin(test1[...,0]))
print(np.amin(test1[...,1]))

[[32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 ...
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]]
[[32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 ...
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]
 [32768 32768 32768 ... 32768 32768 32768]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.0
0.0
0.0
0.0
